#!/bin/sh

read loadavg1 loadavg5 loadavg15 rest < /proc/loadavg
numcpus=$(grep -c '^processor' /proc/cpuinfo)


awk \
  -v failthold=1 \
  -v warnthold=0.7 \
  -v loadavg=${loadavg5} \
  -v numcpus=${numcpus} \
  'BEGIN {
    ratio=loadavg/numcpus
    if (ratio > failthold)
    {
      print "Average load over the last minute is " ratio
      exit 2
    }
    if (ratio > warnthold)
    {
      print "Average load over the last minute is " ratio
      exit 1
    }
    exit 0
  }'
