#!/bin/sh

free --bytes | awk \
  -v failthold=0.90 \
  -v warnthold=0.70 \
  '/^Mem:/{
    cached=$7
    buffers=$6
    used=$3
    total=$2
    # WARNING: `free --bytes` output depends on the version of Ubuntu you run the command on
    # ratio=(used-(buffers+cached))/total
    ratio=used/total
    if (ratio > failthold)
    {
      print "Memory usage ratio is " ratio
      exit 2
    }
    if (ratio > warnthold)
    {
      print "Memory usage ratio is " ratio
      exit 1
    }
    exit 0
  }'
